# Generated by Django 3.1.7 on 2021-05-22 09:37

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComingSooon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pictures')),
            ],
        ),
        migrations.CreateModel(
            name='MovieDetailss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField()),
                ('moviename', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('categories', models.CharField(blank=True, choices=[('popular', 'popular'), ('comingsoon', 'comingsoon'), ('toprated', 'toprated'), ('flop', 'flop')], max_length=250, null=True)),
                ('rating', models.FloatField()),
                ('heroorgname', models.CharField(max_length=150)),
                ('img_hero', models.ImageField(upload_to='pictures')),
                ('heroinorgname', models.CharField(max_length=150)),
                ('img_heroine', models.ImageField(upload_to='pictures')),
                ('anotherartistorgname', models.CharField(max_length=150)),
                ('img_artist1', models.ImageField(upload_to='pictures')),
                ('anotherartistorgname2', models.CharField(max_length=150)),
                ('img_artist2', models.ImageField(upload_to='pictures')),
                ('heromoviename', models.CharField(max_length=150)),
                ('heroinmoviename', models.CharField(max_length=150)),
                ('anotherartistmoviename', models.CharField(max_length=150)),
                ('anotherartistmoviename2', models.CharField(max_length=150)),
                ('director', models.CharField(max_length=150)),
                ('writer', models.CharField(max_length=150)),
                ('genere', models.CharField(max_length=150)),
                ('rlsdate', models.CharField(max_length=150)),
                ('runtime', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='pictures')),
                ('trailerlink', embed_video.fields.EmbedVideoField()),
                ('traillername', models.CharField(max_length=250)),
                ('trillerimg', models.ImageField(upload_to='pictures')),
                ('video_song_img', models.ImageField(blank=True, upload_to='pictures')),
                ('video_song_name', models.CharField(blank=True, max_length=100)),
                ('video_song_link', embed_video.fields.EmbedVideoField(blank=True)),
                ('video_song_img2', models.ImageField(blank=True, upload_to='pictures')),
                ('video_song_name2', models.CharField(blank=True, max_length=100)),
                ('video_song_link2', embed_video.fields.EmbedVideoField(blank=True)),
                ('video_song_name3', models.CharField(blank=True, max_length=100)),
                ('video_song_img3', models.ImageField(blank=True, upload_to='pictures')),
                ('video_song_link3', embed_video.fields.EmbedVideoField(blank=True)),
                ('video_song_img4', models.ImageField(blank=True, upload_to='pictures')),
                ('video_song_name4', models.CharField(blank=True, max_length=100)),
                ('video_song_link4', embed_video.fields.EmbedVideoField(blank=True)),
                ('video_song_img5', models.ImageField(blank=True, upload_to='pictures')),
                ('video_song_name5', models.CharField(blank=True, max_length=100)),
                ('video_song_link5', embed_video.fields.EmbedVideoField(blank=True)),
                ('video_song_img6', models.ImageField(blank=True, upload_to='pictures')),
                ('video_song_name6', models.CharField(blank=True, max_length=100)),
                ('video_song_link6', embed_video.fields.EmbedVideoField(blank=True)),
                ('video_song_img7', models.ImageField(blank=True, upload_to='pictures')),
                ('video_song_name7', models.CharField(blank=True, max_length=100)),
                ('video_song_link7', embed_video.fields.EmbedVideoField(blank=True)),
            ],
        ),
    ]
