# Generated by Django 3.1.7 on 2021-05-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetailss',
            name='categories',
        ),
    ]
