# Generated by Django 3.1.7 on 2021-05-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_remove_moviedetailss_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetailss',
            name='categories',
            field=models.CharField(blank=True, choices=[('popular', 'popular'), ('comingsoon', 'comingsoon'), ('toprated', 'toprated'), ('flop', 'flop')], max_length=250, null=True),
        ),
    ]
