# Generated by Django 3.1.7 on 2021-05-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_moviedetailss_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetailss',
            name='categories',
            field=models.CharField(choices=[('popular', 'popular'), ('comingsoon', 'comingsoon'), ('toprated', 'toprated'), ('flop', 'flop')], default=1, max_length=250),
            preserve_default=False,
        ),
    ]
