# Generated by Django 3.1.7 on 2021-05-24 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_auto_20210523_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetailss',
            name='video_song_img5',
        ),
        migrations.RemoveField(
            model_name='moviedetailss',
            name='video_song_img6',
        ),
        migrations.RemoveField(
            model_name='moviedetailss',
            name='video_song_img7',
        ),
        migrations.RemoveField(
            model_name='moviedetailss',
            name='video_song_link5',
        ),
        migrations.RemoveField(
            model_name='moviedetailss',
            name='video_song_link6',
        ),
        migrations.RemoveField(
            model_name='moviedetailss',
            name='video_song_link7',
        ),
        migrations.RemoveField(
            model_name='moviedetailss',
            name='video_song_name5',
        ),
        migrations.RemoveField(
            model_name='moviedetailss',
            name='video_song_name6',
        ),
        migrations.RemoveField(
            model_name='moviedetailss',
            name='video_song_name7',
        ),
    ]
