# Generated by Django 3.1.7 on 2021-05-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_auto_20210524_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pictures')),
                ('tittle', models.CharField(max_length=250)),
                ('desc', models.TextField()),
            ],
        ),
    ]
